spring:
  application:
    name: KioomStock

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    show-sql: true

logging:
  level:
    root: info
    com.sjoh.kioomstock: debug
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

kiwoom:
  api:
    base-url: "https://api.kiwoom.com"
    key: ""
    secret: ""
    customer-id: ""
