spring:
  application:
    name: KioomStock
#  main:
#    web-application-type: none # ? ??(Tomcat)? ??? ?? ???? ???? ?

logging:
  level:
    root: info
    com.sjoh.kioomstock: debug # ??? ??? ??? ??? ??
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # ?? ??? ??? ??

kiwoom:
  api:
    # ???? REST API ??
    base-url: "https://openapi.kiwoom.com"
    key: "" # ?? Open API App Key
    secret: "" # ?? Open API App Secret
    customer-id: "" # ?? ID (???)
